### ISSUE TITLE
Add AJAX support to eetlijst

### ISSUE THREAD

**Issue by damienallen** [damienallen/ds4reboot#11]
Add AJAX for eetlijst and quick access. Also decide on default spongbob behavior.

**Needs lots of testing.**

**Comment by davidzwa** [comment]
Currently signup_form is with AJAX now. #40

**Comment by davidzwa** [comment]
Problems with AJAX via different url's. Help required. @damienallen

**Comment by davidzwa** [comment]
- [AJAXify shopping cart icon. ]
