### ISSUE TITLE
Small issues (split)

### ISSUE THREAD

**Issue by davidzwa** [damienallen/ds4reboot#13]
Opening eetlijst in small screen version does not change day to current day.
(So small-window html template needs day change)
David is stuck at Woensdag
Karel is stuck at Woensdag

**Comment by davidzwa** [comment]
Eetlijst says 'Kost invullen' should be 'Kosten invullen'

**Comment by damienallen** [comment]
It looks like the date was being cached, we'll see tonight if the hotfix worked.

Also, there will probably be plenty of Dutch spelling/grammar mistakes, let's keep them separate: #15

**Comment by davidzwa** [comment]
Issue report [9 Sept. 2016, 18:45]
PC GR keeps logged in and people fill in costs on wrong account per accident.
Option 1: reduce login session timeout
Option 2: allow removing cost-entry for either logged in account or give admin that right.
Option 3: make logged in acount more visible or show it next to cost transaction

**Comment by davidzwa** [comment]
Stat report

Eetlijst takes long to load compared to bierlijst. Future maybe pre-fetch (http method) and post-fetch eetlijst data (ajax)?

Is this related to
[https://github.com/damienallen/ds4reboot/issues/11](url) ?

**Comment by davidzwa** [comment]
>>Issue report[10 Sept. 2016, 15:10]

Clicking white-wine/red-wine dropdown and clicking it again (de-selection) reloads the beer-list.
Clicking outside dropdown (not the arrow) doesnt do this. Implement same cancel procedure.

>>2nd issue

Red-wine/white-wine is not big: hard to click.
Advise: use red and yellow icon instead of text. 
Advise2: collapse dropdown sideways

**Comment by damienallen** [comment]
David, please use a separate issue for each report, there were split into #20, #21, #22.

**Comment by damienallen** [comment]
The original bug was fixed so this issue will be closed.
