### ISSUE TITLE
Fix eetlijst quickaccess

### ISSUE THREAD

**Issue by damienallen** [damienallen/ds4reboot#2]
Old eetlijst quick access form was broken when AJAX was added for bierlijst.

**Comment by davidzwa** [comment]
Please give detail about bug so I can understand.

**Comment by damienallen** [comment]
In quick_access.html you can remove the `{% comment %}` and `{% endcomment %}` tags. That snippit of code stopped working once the bierlijst section was moved to ajax.

**Comment by damienallen** [comment]
@davidzwa You need to make a pull request for the eetlijst-quickaccess branch which is on your laptop.
