### ISSUE TITLE
Wine turf button enchancements

### ISSUE THREAD

**Issue by damienallen** [damienallen/ds4reboot#22]
Issue report[10 Sept. 2016, 15:10]
Clicking white-wine/red-wine dropdown and clicking it again (de-selection) reloads the beer-list.
Clicking outside dropdown (not the arrow) doesnt do this. Implement same cancel procedure.

2nd issue
Red-wine/white-wine is not big: hard to click.
Advice: use red and yellow icon instead of text. 
Advice2: collapse dropdown sideways

**Comment by davidzwa** [comment]
#50
