### ISSUE TITLE
Filling costs error

### ISSUE THREAD

**Issue by davidzwa** [damienallen/ds4reboot#45]
![untitled](https://cloud.githubusercontent.com/assets/6005355/18480577/78b59ea2-79d9-11e6-9d6f-0ea497a1632e.png)

**Comment by davidzwa** [comment]
Damien, could you tell me why Decimal is necessary?

**Comment by davidzwa** [comment]
New bug appeared. Fix is not trivial:
- either dont allow cook for one person
- or dont split costs when only cook
![untitled2](https://cloud.githubusercontent.com/assets/6005355/18481649/37beb0ba-79dd-11e6-9896-687b7e2ba5d3.png)

**Comment by damienallen** [comment]
Which branch is this?

**Comment by davidzwa** [comment]
#47
